### ISSUE TITLE
Price Oracle Epic

### ISSUE THREAD

**Issue by epiro-ps** [ArdanaLabs/Ardana-dApps#73]
## Tasks

The completion of the following tasks marks the completion of the Price Oracle MVP:

- [ ] https://github.com/ArdanaLabs/Ardana-dApps/issues/67
- [ ] https://github.com/ArdanaLabs/Ardana-dApps/issues/71
- [ ] https://github.com/ArdanaLabs/Ardana-dApps/issues/70
- [ ] https://github.com/ArdanaLabs/Ardana-dApps/issues/69
- [ ] https://github.com/ArdanaLabs/Ardana-dApps/issues/72

## Issue Dependency Graph
![po dot](https://user-images.githubusercontent.com/98818692/201990848-fa28aea7-50a8-4077-a336-6c34d988d78a.png)
